//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRShooterKit : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Joystick
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_Joystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickPress
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_JoystickPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryButton
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_PrimaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryButton
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_SecondaryButton;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftHand
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_LeftHand;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHand
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_RightHand;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.vRShooterKit_Haptic;
            }
        }
    }
}
